version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  snake-game:
    build: .
    container_name: snake-game
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/snake_scores
